config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    root 'pages#top'

    get 'pages/study_1'
    get 'pages/study_2'
    get 'pages/study_2_modal'
    get 'pages/study_3'
    get 'pages/study_4'
    get 'pages/study_5'
    get 'pages/study_7'
    get 'pages/study_8'
    resources :study_items, only: [:index, :new, :edit, :create, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  class << self
    alias_method :i18n, :human_attribute_name

    def i18n_name(options = {})
      model_name.human(options)
    end
  end
end

app/models/study_item.rb
class StudyItem < ApplicationRecord
  has_many :study_items_subitems, dependent: :destroy
  has_many :study_subitems, through: :study_items_subitems


  # default_scope { where('code_no > ?', 2000) }

  scope :upper_2000, -> { where('code_no > ?', 2000) }
  scope :upper_3000, -> { where('code_no > ?', 3000) }
  scope :upper, -> (threshold) { where('code_no > ?', threshold) }
  scope :upper_even, -> (threshold) { where('code_no > ?', threshold) if threshold % 2 == 0 }

  def self.list
    StudyItemDecorator.decorate_collection(StudyItem.all)
  end
end

app/models/study_items_subitem.rb
class StudyItemsSubitem < ApplicationRecord
  belongs_to :study_item
  belongs_to :study_subitem
end

app/models/study_subitem.rb
class StudySubitem < ApplicationRecord
  has_many :study_items_subitems
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :set_locale

  private

  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = locale_in_params || locale_in_accept_language || I18n.default_locale
  end

  def locale_in_params
    if params[:locale].present?
      params[:locale].to_sym.presence_in(I18n::available_locales) || I18n.default_locale
    else
      nil
    end
  end

  def locale_in_accept_language
    request.env['HTTP_ACCEPT_LANGUAGE']
        .to_s # nil 対策
        .split(',')
        .map{ |_| _[0..1].to_sym }
        .select { |_| I18n::available_locales.include?(_) }
        .first
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end

  def study_1
  end

  def study_2
  end

  def study_3
  end

  def study_5
    @study_items = StudyItem.all
  end
end

app/controllers/study_items_controller.rb
class StudyItemsController < ApplicationController
  before_action :set_study_item, only: [:edit, :update, :destroy]
  def index
    set_study_items
  end

  def new
    @study_item = StudyItem.new
  end

  def edit

  end

  def create
    StudyItem.transaction do
      StudyItem.create!(study_item_create_params)
    end
    @message = { notice: t('.prompt.notice') }
  rescue => e
    @message = { alert: t('.prompt.alert', error: e.message) }
  ensure
    set_study_items
    render 'study_items/update'
  end

  def update
    StudyItem.transaction do
      @study_item.update!(study_item_update_params)
    end
    @message = { notice: t('.prompt.notice') }
  rescue => e
    @message = { alert: t('.prompt.alert', error: e.message) }
  ensure
    set_study_items
    render 'study_items/update'
  end

  def destroy
    StudyItem.transaction do
      @study_item.destroy!
    end
    @message = { notice: t('.prompt.notice') }
  rescue => e
    @message = { alert: t('.prompt.alert', error: e.message) }
  ensure
    set_study_items
    render 'study_items/update'
  end

  private

  def set_study_items
    @study_items = StudyItem.list
  end

  def set_study_item
    @study_item = StudyItem.find(params[:id])
  end

  def study_item_create_params
    params.require(:study_item).permit(:name, :code_no)
  end

  def study_item_update_params
    params.require(:study_item).permit(:name, :code_no)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/study_items_helper.rb
module StudyItemsHelper
  def to_date_text(datetime)
    return '' if datetime.blank?
    datetime.localtime.strftime('%Y/%m/%d')
  end

  def study_sub_item_options
    StudySubitemDecorator.decorate_collection(StudySubitem.all).map do |study_subitem|
      [study_subitem.full_name, study_subitem.id]
    end
  end
end

app/views/layouts/_flash_message.html.erb
<% if message.present? && message[:notice].present? %>
    <div class="alert alert-success"><%== message[:notice].html_safe %></div>
<% end %>

<% if message.present? && message[:alert].present? %>
    <div class="alert alert-danger">
      <%== message[:alert].html_safe %>
      <%= button_tag class: 'btn btn-sm btn-danger button-close' do %>
          <%= t('view.button.close') %>
      <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flash-message-container" class="text-right" style="display: none"></div>
    <%= yield %>
    <div id="common-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  </body>

</html>

app/views/pages/_study_2_modal.html.erb
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">
        <span>Chapter 4</span>
      </h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <table class="table">
        <tbody>
        <tr>
          <th>ATOKYO</th>
          <td>
            <%= link_to '#', class: 'btn btn-sm btn-primary link-copy' do %>
                <i class="far fa-copy"></i>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>GARAGE-R</th>
          <td>
            <%= link_to '#', class: 'btn btn-sm btn-primary link-copy' do %>
                <i class="far fa-copy"></i>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>Mitsuichem</th>
          <td>
            <%= link_to '#', class: 'btn btn-sm btn-primary link-copy' do %>
                <i class="far fa-copy"></i>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">
        Close
      </button>
    </div>
  </div>
</div>
<script>
    Study.study_2.chap_4_modal();
</script>

app/views/pages/study_1.html.erb
<a href="http://www.webdesignleaves.com/wp/jquery/1631/" target="_blank">http://www.webdesignleaves.com/wp/jquery/1631/</a>
<div class="container">
  <span>container</span>
  <div class="row">
    <div class="col-12 text-right">
      <%= link_to '#', class: 'link-add btn btn-primary' do %>
          <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
  <div class="table-container row" style="border: solid 1px">
    <span>table-container</span>
    <div class="table-content col-12" style="border: solid 1px">
      <span>table-content</span>
      <table class="table table-bordered">
        <thead>
        <tr>
          <th>TABLE</th>
          <th></th>
        </tr>
        </thead>
        <tbody class="tbody">
        <tr class="tr">
          <td class="td-item">ITEM</td>
          <td>
            <%= link_to '#', class: 'link-delete' do %>
                <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<table style="display: none">
  <tbody class="tbody-dummy">
  <tr class="tr">
    <td class="td-item">ITEM</td>
    <td>
      <%= link_to '#', class: 'link-delete' do %>
          <i class="fas fa-trash-alt"></i>
      <% end %>
    </td>
  </tr>
  </tbody>
</table>
<script>
    Study.study_1.chap_1_1();
    //Study.study_1.chap_1_2();
    //Study.study_1.chap_1_2_re_call();
    //Study.study_1.chap_1_3();
    //Study.study_1.chap_1_3_small();
    //Study.study_1.chap_1_4();
    //Study.study_1.chap_1_4_block();
    //Study.study_1.chap_1_5();
</script>

app/views/pages/study_2.html.erb
<a href="http://api.jquery.com/trigger/" target="_blank">http://api.jquery.com/trigger/</a>
<div class="container">
  <div class="row my-5">
    <div id="button-chap-1" class="col-2 offset-5 border text-center">
      <labe>Chapter 1 Click</labe>
    </div>
  </div>

  <div class="row my-5">
    <div id="content-chap-2-1" class="col-4 offset-4 border text-center">
      <button id="button-chap-2-1">Chapter 2-1 ATA-Click</button>
    </div>
  </div>

  <div class="row my-5">
    <div id="content-chap-2-2" class="col-4 offset-4 border text-center">
      <button id="button-chap-2-2">Chapter 2-2 ATA-Click</button>
    </div>
  </div>

  <div class="row my-5">
    <div class="col-4 offset-4 border text-center">
      <input name="chap_3_1" type="text"/>
      <button id="button-chap-3-1">Chapter 3-1 ATA-Click ARGS</button>
    </div>
  </div>

  <div class="row my-5">
    <div class="col-6 offset-3 border text-center">
      <input name="chap_3_2_1" class="input-first" type="text" placeholder="First Name"/>
      <input name="chap_3_2_2" class="input-family" type="text" placeholder="Family Name"/>
      <button id="button-chap-3-2">Chapter 3-2 ATA-Click ARGS Array</button>
    </div>
  </div>

  <div class="row my-5">
    <div class="col-6 offset-3 border text-center">
      <input name="chap_3_3_1" class="input-first" type="text" placeholder="First Name"/>
      <input name="chap_3_3_2" class="input-family" type="text" placeholder="Family Name"/>
      <button id="button-chap-3-3">Chapter 3-3 ATA-Click ARGS Object</button>
    </div>
  </div>

  <div class="row my-5">
    <div class="col-6 offset-3 border text-center">
      <%= text_field 'chap_3_4', '', id: 'input-chap-4', class: 'form-control', placeholder: 'Answer' %>
      <%= link_to pages_study_2_modal_path, remote: true, class: 'btn btn-primary' do %>
          Chapter 4
      <% end %>
    </div>
  </div>
</div>

<div id="common-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<script>
    Study.study_2.chap_1();
    Study.study_2.chap_2_1();
    Study.study_2.chap_2_2();
    Study.study_2.chap_3_1();
    Study.study_2.chap_3_2();
    Study.study_2.chap_3_3();
    Study.study_2.chap_4();
</script>

app/views/pages/study_2_modal.js.erb
$('#common-modal').html("<%= escape_javascript(render 'study_2_modal') %>");
$('#common-modal').modal();

app/views/pages/study_3.html.erb
https://railsguides.jp/active_record_migrations.html
<div class="container">
  <div class="row my-4">
    <div class="col-12">
      <h3>changeで自動rollback可能(reversible)なコマンド一覧</h3>
      <pre class="card">
        add_column
        remove_column（型を指定しなければならない）

        add_foreign_key
        remove_foreign_key（2番目のテーブルを指定しなければならない）

        add_index
        remove_index

        add_reference
        remove_reference

        add_timestamps
        remove_timestamps

        create_table
        drop_table （ブロックを渡さなければならない）

        create_join_table
        drop_join_table

        disable_extension (PostgreSQL用）
        enable_extension (PostgreSQL用）

        change_column_default (:fromと:toの指定は省略できない)
        change_column_null

        rename_column
        rename_index
        rename_table
      </pre>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-6">
      <label>study_items</label>
      <pre class="card">
    create_table :study_items do |t|
      t.string :name
      t.string :code

      t.timestamps
    end
      </pre>
    </div>
    <div class="col-6">
      <label>study_subitems</label>
      <pre class="card">
    create_table :study_subitems do |t|
      t.string :name
      t.string :code

      t.timestamps
    end
      </pre>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-12">
      <p>rails db:rollback STEP=5</p>
      <p>'study_items作成'<br>rails db:migrate VERSION=20190413044054</p>
      <p>'study_subitems作成'<br>rails db:migrate VERSION=20190413044105</p>
      <p>rails db:populate:study_3</p>
      <p>'study_itemsとstudy_itemsをreference結合'<br>rails db:migrate VERSION=20190414082314</p>
      <p>'codeをcode_noにカラム名を変更し、integerに変更、null:falseに設定'<br>rails db:migrate VERSION=20190414105927</p>
      <p>'中間テーブルを定義してstudy_itemsとstudy_sub_itemsを多対多に変更'<br>rails db:migrate VERSION=20190414125534</p>
    </div>
  </div>

</div>

app/views/pages/study_5.html.erb
<div class="container">
  https://railsguides.jp/working_with_javascript_in_rails.html
  <% study_item_1 = @study_items.first %>
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Code</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= study_item_1.name %></td>
          <td><%= study_item_1.code_no %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table">
        <tbody>
        <tr>
          <td>
            <%= link_to edit_study_item_path(study_item_1) do %>
                <i class="fas fa-edit fa-fw"></i>link:html
            <% end %>
          </td>
          <td>
            <%= link_to edit_study_item_path(study_item_1, format: :json) do %>
                <i class="fas fa-edit fa-fw"></i>link:json
            <% end %>
          </td>
          <td>
            <%= link_to edit_study_item_path(study_item_1, format: :js) do %>
                <i class="fas fa-edit fa-fw"></i>link:js
            <% end %>
          </td>
          <td>
            <%= link_to edit_study_item_path(study_item_1, format: :csv) do %>
                <i class="fas fa-edit fa-fw"></i>link:csv
            <% end %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to edit_study_item_path(study_item_1, format: :html), remote: true, class: 'remote-link' do %>
                <i class="fas fa-edit fa-fw"></i>remote:html
            <% end %>
          </td>
          <td>
            <%= link_to edit_study_item_path(study_item_1, format: :json), remote: true, class: 'remote-link' do %>
                <i class="fas fa-edit fa-fw"></i>remote:json
            <% end %>
          </td>
          <td>
            <%= link_to edit_study_item_path(study_item_1, format: :js), remote: true, class: 'remote-link' do %>
                <i class="fas fa-edit fa-fw"></i>remote:js
            <% end %>
          </td>
          <td>
            <%= link_to edit_study_item_path(study_item_1, format: :csv), remote: true, class: 'remote-link' do %>
                <i class="fas fa-edit fa-fw"></i>remote:csv
            <% end %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to '#', class: 'ajax-format-html-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:format:html
            <% end %>
          </td>
          <td>
            <%= link_to '#', class: 'ajax-format-json-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:format:json
            <% end %>
          </td>
          <td>
            <%= link_to '#', class: 'ajax-format-js-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:format:js
            <% end %>
          </td>
          <td>
            <%= link_to '#', class: 'ajax-format-csv-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:format:csv
            <% end %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to '#', class: 'ajax-data-html-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:dataType:html
            <% end %>
          </td>
          <td>
            <%= link_to '#', class: 'ajax-data-json-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:dataType:json
            <% end %>
          </td>
          <td>
            <%= link_to '#', class: 'ajax-data-script-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:dataType:script
            <% end %>
          </td>
          <td>
            <%= link_to '#', class: 'ajax-data-text-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:dataType:text
            <% end %>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <%= link_to '#', class: 'ajax-format-html-data-json-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:format:html:dataType:json
            <% end %>
          </td>
          <td colspan="2">
            <%= link_to '#', class: 'ajax-format-json-data-html-link' do %>
                <i class="fas fa-edit fa-fw"></i>ajax:format:json:dataType:html
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div id="result">

      </div>
      <div id="error" style="color: red">

      </div>
    </div>
  </div>
</div>
<script>
    Study.study_5.remoteLink();
</script>

app/views/pages/study_8.html.erb
<style>
  dd {
    padding: 0.5rem;
  }

  dd pre {
    background-color: #dddddd;
    padding: 0.5rem;
  }
</style>
<div class="container">
  <h1 class="text-center">Rails国際化 (I18n) API</h1>
  <ul>
    <li>https://railsguides.jp/i18n.html</li>
    <li>https://qiita.com/Kta-M/items/bd4ba36a58ad602a9d8b</li>
    <li>https://qiita.com/youcune/items/44c3b41c23ffcf091abe</li>
  </ul>
  <div class="row">
    <div class="col-12">
      <h2>推奨言語切り替え方法</h2>
      <dl>
        <dt>2.2.5 セッションやcookieに含まれるロケールの保存について</dt>
        <dd>開発者は、選択したロケールをセッションやcookieに保存したくなる誘惑にかられるかもしれません。しかしこれは行ってはいけません。ロケールは透過的であるべきで、かつURLの一部に含めるべきです。こうすることで、ユーザーがweb自体に対して抱く基本的な前提を崩さずに済みます。あなたがそのURLを知人に送れば、あなたが見ているのとまったく同じページとコンテンツを知人も見ることができます。この前提を表す重要な言い回しが「RESTfulである」ということです。RESTfulアプローチについて詳しくは、Stefan Tilkovの記事を参照してください。RESTfulというルールから外れる場合もありますが、それについては後述します。</dd>
        <dd>
          <ul>
            <li><%= link_to 'TOP', root_path %></li>
            <li><%= link_to 'Study Item', study_items_path %></li>
          </ul>
        </dd>
        <dd>
          config/initializers/locale.rb
          <pre>
I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}').to_s]

I18n.available_locales = [:en, :ja]

I18n.default_locale = :ja</pre>
        </dd>
        <dd>
          controllers/application_controller.rb
          <pre>
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :set_locale

  private

  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = locale_in_params || locale_in_accept_language || I18n.default_locale
  end

  def locale_in_params
    if params[:locale].present?
      params[:locale].to_sym.presence_in(I18n::available_locales) || I18n.default_locale
    else
      nil
    end
  end

  def locale_in_accept_language
    request.env['HTTP_ACCEPT_LANGUAGE']
        .to_s # nil 対策
        .split(',')
        .map{ |_| _[0..1].to_sym }
        .select { |_| I18n::available_locales.include?(_) }
        .first
  end

end</pre>
        </dd>
        <dd>
          config/routes.rb
          <pre>
scope "(:locale)", locale: /en|ja/ do
    root 'pages#top'
    get 'pages/study_1'
end</pre>
        </dd>
      </dl>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <h2>Enumの表現</h2>
      <dl>
        <dt>4.5 Active Recordモデルで翻訳を行なう</dt>
        <dd>
          <pre>
ja:
  activerecord:
    models:
      study_item: スタディアイテム
    attributes:
      study_item:
        name: 名前
        code_no: コード番号
        gender: 性別
      study_item/gender:
        male: 男性
        female: 女性</pre>
        </dd>
      </dl>
    </div>
  </div>
</div>
<script>

</script>

app/views/pages/top.html.erb
<div class="container">
  <h1>Pages#top</h1>
  <p>Find me in app/views/pages/top.html.erb</p>
</div>

app/views/study_items/_modal.html.erb
<div class="modal-dialog modal-md">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">
        <i class="fas fa-balance-scale fa-fw"></i>
        <span><%= title %></span>
      </h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_with model: @study_item, id: 'form-study-item', class: 'form-horizontal' do |f| %>
        <div class="modal-body">
          <div class="form-group row">
            <%= f.label :name, class: 'col-form-label col-4' %>
            <div class="col-8">
              <%= f.text_field :name, class: 'form-control', required: true %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :code_no, class: 'col-form-label col-4' %>
            <div class="col-8">
              <%= f.text_field :code_no, class: 'form-control', required: true %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag class: 'btn btn-lg btn-primary button-submit' do %>
            <i class="<%= button_icon %> fa-fw"></i>
            <%= button_label %>
          <% end %>
          <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">
            <%= t('view.button.cancel') %>
          </button>
        </div>
    <% end %>
  </div>
</div>

app/views/study_items/_table.html.erb
<table class="table">
  <tbody>
  <thead>
  <tr>
    <th><%= StudyItem.human_attribute_name('name') %></th>
    <th><%= StudyItem.human_attribute_name('code_no') %></th>
    <th>Date</th>
    <th>Badge</th>
    <th>Select</th>
    <th colspan="2">
      <%= link_to new_study_item_path, remote: true, class: 'btn btn-primary btn-sm' do %>
          <i class="fas fa-plus"></i>
      <% end %>
    </th>
  </tr>
  </thead>
  <% study_items.each do |study_item| %>
      <tr>
        <td><%= study_item.name %></td>
        <td><%= study_item.code_no %></td>
        <td><%= study_item.created_at_text %></td>
        <td><%== study_item.code_badge_html %></td>
        <td><%= select_tag 'dummy', options_for_select(study_sub_item_options), class: 'form-control-sm' %></td>
        <td>
          <%= link_to edit_study_item_path(study_item), remote: true do %>
              <i class="far fa-edit"></i>
          <% end %>
        </td>
        <td>
          <%= link_to study_item, method: :delete, remote: true, data: {confirm: t('view.label.confirm_delete', name: StudyItem.model_name.human)} do %>
              <i class="far fa-trash-alt"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/study_items/edit.html.erb
<h1>format:html</h1>

app/views/study_items/edit.js.erb
$('#common-modal').html("<%= escape_javascript(render 'modal',
  title: t('.title'), button_icon: 'fas fa-sync-alt', button_label: t('view.button.do_update')) %>");
$('#common-modal').modal();

app/views/study_items/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-12">
      <h1><%= t('.title') %><small><%= StudyItem.model_name.human %></small></h1>
      <div class="table-container">
        <%= render 'table', study_items: @study_items %>
      </div>
      <h3><%= StudyItem.i18n_name %></h3>
      <h3><%= StudyItem.i18n('name') %></h3>
      <h3><%= StudyItem.i18n('gender') %></h3>
      <h3><%= StudyItem.i18n('gender.male') %></h3>
      <h3><%= StudyItem.i18n('gender.female') %></h3>
    </div>
  </div>
</div>

app/views/study_items/new.js.erb
$('#common-modal').html("<%= escape_javascript(render 'modal',
  title: t('.title'), button_icon: 'fas fa-plus', button_label: t('view.button.do_create')) %>");
$('#common-modal').modal();

app/views/study_items/update.js.erb
$('#common-modal').modal('hide');
$('.table-container').html("<%= escape_javascript(render 'table', study_items: @study_items) %>");
$('#flash-message-container').html("<%= escape_javascript(render 'layouts/flash_message', message: @message) %>");
Study.study_items.show_message();